# Generated by Django 5.1.3 on 2024-11-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
